/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.admin;

/**
 *
 * @author Yash
 */
public class AddCourseOffering extends javax.swing.JPanel {

    /**
     * Creates new form AddCourseOffering
     */
    public AddCourseOffering() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cIDLabel = new javax.swing.JLabel();
        courseID = new javax.swing.JTextField();
        semLabel = new javax.swing.JLabel();
        sem = new javax.swing.JTextField();
        facultyLabel = new javax.swing.JLabel();
        faculty = new javax.swing.JTextField();
        dayLabel = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        cStartLabel = new javax.swing.JLabel();
        classStart = new javax.swing.JTextField();
        cEndLabel = new javax.swing.JLabel();
        classEnd = new javax.swing.JTextField();
        classSize = new javax.swing.JTextField();
        cSizeLabel = new javax.swing.JLabel();
        wlSizeLabel = new javax.swing.JLabel();
        waitlist = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();

        cIDLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cIDLabel.setText("Course Id : ");

        courseID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        semLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        semLabel.setText("Semester :");

        sem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        facultyLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        facultyLabel.setText("Faculty Name(s) :");

        faculty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dayLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dayLabel.setText("Days of the Week :");

        day.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cStartLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cStartLabel.setText("Class Start Time :");

        classStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cEndLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cEndLabel.setText("Class End Time :");

        classEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        classSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cSizeLabel.setText("Class Size :");

        wlSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wlSizeLabel.setText("Wait List Size :");

        waitlist.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setText("Submit");

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Go Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(day))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(facultyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cStartLabel)
                            .addComponent(cEndLabel)
                            .addComponent(cSizeLabel)
                            .addComponent(wlSizeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classStart)
                            .addComponent(classEnd)
                            .addComponent(classSize)
                            .addComponent(waitlist, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(semLabel)
                        .addGap(26, 26, 26)
                        .addComponent(sem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(submit)
                        .addGap(51, 51, 51)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseID)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cIDLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semLabel)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyLabel)
                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLabel)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cStartLabel)
                    .addComponent(classStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cEndLabel)
                    .addComponent(classEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSizeLabel))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wlSizeLabel)
                    .addComponent(waitlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(back))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel cEndLabel;
    private javax.swing.JLabel cIDLabel;
    private javax.swing.JLabel cSizeLabel;
    private javax.swing.JLabel cStartLabel;
    private javax.swing.JTextField classEnd;
    private javax.swing.JTextField classSize;
    private javax.swing.JTextField classStart;
    private javax.swing.JTextField courseID;
    private javax.swing.JTextField day;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField faculty;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JTextField sem;
    private javax.swing.JLabel semLabel;
    private javax.swing.JButton submit;
    private javax.swing.JTextField waitlist;
    private javax.swing.JLabel wlSizeLabel;
    // End of variables declaration//GEN-END:variables
}
