/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.admin;

import dbpro.AdminViewController;

/**
 *
 * @author Yash
 */
public class AdminHomePage extends javax.swing.JPanel {

    /**
     * Creates new form AdminHomePage
     */
    public AdminHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        viewStudent = new javax.swing.JButton();
        viewProfile = new javax.swing.JButton();
        enrollStudent = new javax.swing.JButton();
        viewAddCourse = new javax.swing.JButton();
        viewAddCourseOffering = new javax.swing.JButton();
        specialEnrollment = new javax.swing.JButton();
        deadline = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(51, 0, 153));
        welcomeLabel.setText("Welcome Admin!");

        viewStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewStudent.setForeground(new java.awt.Color(0, 51, 153));
        viewStudent.setText("View Student's Details");
        viewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentActionPerformed(evt);
            }
        });

        viewProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewProfile.setForeground(new java.awt.Color(0, 51, 153));
        viewProfile.setText("View My Profile");
        viewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileActionPerformed(evt);
            }
        });

        enrollStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enrollStudent.setForeground(new java.awt.Color(0, 51, 153));
        enrollStudent.setText("Enroll a new Student");
        enrollStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollStudentActionPerformed(evt);
            }
        });

        viewAddCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewAddCourse.setForeground(new java.awt.Color(0, 51, 153));
        viewAddCourse.setText("View/Add Courses");
        viewAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddCourseActionPerformed(evt);
            }
        });

        viewAddCourseOffering.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewAddCourseOffering.setForeground(new java.awt.Color(0, 51, 153));
        viewAddCourseOffering.setText("View/Add Course Offering");
        viewAddCourseOffering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddCourseOfferingActionPerformed(evt);
            }
        });

        specialEnrollment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        specialEnrollment.setForeground(new java.awt.Color(0, 51, 153));
        specialEnrollment.setText("View/Approve Special Enrollment Requests");
        specialEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialEnrollmentActionPerformed(evt);
            }
        });

        deadline.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deadline.setForeground(new java.awt.Color(0, 51, 153));
        deadline.setText("Enforce Add/Drop Deadline");
        deadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlineActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 51, 153));
        logout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAddCourseOffering, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(enrollStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(specialEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAddCourseOffering, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(specialEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentActionPerformed
        // TODO add your handling code here:
        AdminViewController.showViewStudentDetails();
    }//GEN-LAST:event_viewStudentActionPerformed

    private void viewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileActionPerformed
        // TODO add your handling code here:
        AdminViewController.showAdminProfile();
    }//GEN-LAST:event_viewProfileActionPerformed

    private void enrollStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollStudentActionPerformed
        // TODO add your handling code here:
        AdminViewController.showEnrollStudent();
    }//GEN-LAST:event_enrollStudentActionPerformed

    private void viewAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddCourseActionPerformed
        // TODO add your handling code here:
        AdminViewController.showViewAddCourse();
    }//GEN-LAST:event_viewAddCourseActionPerformed

    private void viewAddCourseOfferingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddCourseOfferingActionPerformed
        // TODO add your handling code here:
        AdminViewController.showViewAddCourseOffering();
    }//GEN-LAST:event_viewAddCourseOfferingActionPerformed

    private void deadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadlineActionPerformed
        // TODO add your handling code here:
        AdminViewController.showAddDropDeadline();
    }//GEN-LAST:event_deadlineActionPerformed

    private void specialEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialEnrollmentActionPerformed
        // TODO add your handling code here:
        AdminViewController.showSpecialEnrollment();
    }//GEN-LAST:event_specialEnrollmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deadline;
    private javax.swing.JButton enrollStudent;
    private javax.swing.JButton logout;
    private javax.swing.JButton specialEnrollment;
    private javax.swing.JButton viewAddCourse;
    private javax.swing.JButton viewAddCourseOffering;
    private javax.swing.JButton viewProfile;
    private javax.swing.JButton viewStudent;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
