/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.admin;

import Connection.SQL_Helper;
import dbpro.AdminViewController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class ViewCourseOffering extends javax.swing.JPanel {

    /**
     * Creates new form AddCourseOffering
     */
    public ViewCourseOffering() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cIDLabel = new javax.swing.JLabel();
        courseID = new javax.swing.JTextField();
        semLabel = new javax.swing.JLabel();
        sem = new javax.swing.JTextField();
        facultyLabel = new javax.swing.JLabel();
        faculty = new javax.swing.JTextField();
        dayLabel = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        cStartLabel = new javax.swing.JLabel();
        classStart = new javax.swing.JTextField();
        cEndLabel = new javax.swing.JLabel();
        classEnd = new javax.swing.JTextField();
        classSize = new javax.swing.JTextField();
        cSizeLabel = new javax.swing.JLabel();
        wlSizeLabel = new javax.swing.JLabel();
        waitlist = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        showOff = new javax.swing.JButton();
        locationLabel = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cOffLabel = new javax.swing.JLabel();
        cOff = new javax.swing.JTextField();
        find = new javax.swing.JButton();
        back = new javax.swing.JButton();
        curEnrollLabel = new javax.swing.JLabel();
        curEnroll = new javax.swing.JTextField();

        cIDLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cIDLabel.setText("Course Id : ");

        courseID.setEditable(false);
        courseID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        semLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        semLabel.setText("Semester :");

        sem.setEditable(false);
        sem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        facultyLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        facultyLabel.setText("Faculty ID(s) :");

        faculty.setEditable(false);
        faculty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dayLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dayLabel.setText("Days of the Week :");

        day.setEditable(false);
        day.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cStartLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cStartLabel.setText("Class Start Time :");

        classStart.setEditable(false);
        classStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cEndLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cEndLabel.setText("Class End Time :");

        classEnd.setEditable(false);
        classEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        classSize.setEditable(false);
        classSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cSizeLabel.setText("Class Size :");

        wlSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wlSizeLabel.setText("Wait List Size :");

        waitlist.setEditable(false);
        waitlist.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        yearLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearLabel.setText("Year :");

        year.setEditable(false);
        year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        showOff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showOff.setText("Show Course Offering Ids");
        showOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOffActionPerformed(evt);
            }
        });

        locationLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        locationLabel.setText("Class Location :");

        location.setEditable(false);
        location.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("View Course Offering");

        cOffLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cOffLabel.setText("Course Offering Id :");

        cOff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        find.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        find.setText("Find");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        curEnrollLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        curEnrollLabel.setText("Current Enrollment :");

        curEnroll.setEditable(false);
        curEnroll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yearLabel)
                        .addGap(18, 18, 18)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(dayLabel)
                            .addGap(18, 18, 18)
                            .addComponent(day))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(facultyLabel)
                            .addGap(29, 29, 29)
                            .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cOffLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cOff, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(find)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(showOff))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(locationLabel)
                            .addGap(18, 18, 18)
                            .addComponent(location))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(curEnrollLabel)
                            .addGap(18, 18, 18)
                            .addComponent(curEnroll))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cStartLabel)
                                .addComponent(cSizeLabel)
                                .addComponent(wlSizeLabel)
                                .addComponent(cEndLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(classStart)
                                .addComponent(classEnd)
                                .addComponent(classSize)
                                .addComponent(waitlist, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cIDLabel)
                            .addComponent(semLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseID, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(267, 267, 267))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cOffLabel)
                    .addComponent(cOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showOff)
                    .addComponent(find)
                    .addComponent(back))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cIDLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semLabel)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyLabel)
                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLabel)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cStartLabel)
                    .addComponent(classStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cEndLabel)
                    .addComponent(classEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSizeLabel))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wlSizeLabel)
                    .addComponent(waitlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curEnrollLabel)
                    .addComponent(curEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOffActionPerformed
        // TODO add your handling code here:
        AdminViewController.showViewCourseOfferings();
    }//GEN-LAST:event_showOffActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        AdminViewController.closeViewCourseOffering();
        AdminViewController.closeCourseOfferingList();
        AdminViewController.showViewAddCourseOffering();
    }//GEN-LAST:event_backActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        try {
            // TODO add your handling code here:
            ArrayList<String> co= SQL_Helper.get_course_offering_details(Long.parseLong(cOff.getText().trim()));
            int count = Integer.parseInt(co.get(2));
            courseID.setText(co.get(0));
            sem.setText(co.get(1));
            year.setText(co.get(10+count));
          
            int i;
            String faculty_str = "";
            for (i = 0; i < count; i++) {
                faculty_str += co.get(2+i);
            }
            faculty.setText(faculty_str);
            day.setText(co.get(3+count));
            classStart.setText(co.get(4+count));
            classEnd.setText(co.get(5+count));
            classSize.setText(co.get(6+count));
            waitlist.setText(co.get(7+count));
            curEnroll.setText(co.get(8+count));
            location.setText(co.get(9+count));
            
        } catch (SQLException ex) {
             courseID.setText("");
            sem.setText("");
            faculty.setText("");
            day.setText("");
            classStart.setText("");
            classEnd.setText("");
            classSize.setText("");
            waitlist.setText("");
            curEnroll.setText("");
            location.setText("");
            JOptionPane.showMessageDialog(null, "Course Offering ID not found!");  
           
            Logger.getLogger(ViewCourseOffering.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_findActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel cEndLabel;
    private javax.swing.JLabel cIDLabel;
    private javax.swing.JTextField cOff;
    private javax.swing.JLabel cOffLabel;
    private javax.swing.JLabel cSizeLabel;
    private javax.swing.JLabel cStartLabel;
    private javax.swing.JTextField classEnd;
    private javax.swing.JTextField classSize;
    private javax.swing.JTextField classStart;
    private javax.swing.JTextField courseID;
    private javax.swing.JTextField curEnroll;
    private javax.swing.JLabel curEnrollLabel;
    private javax.swing.JTextField day;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField faculty;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JButton find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField location;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField sem;
    private javax.swing.JLabel semLabel;
    private javax.swing.JButton showOff;
    private javax.swing.JTextField waitlist;
    private javax.swing.JLabel wlSizeLabel;
    private javax.swing.JTextField year;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
