/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.admin;

import Connection.SQL_Helper;
import dbpro.AdminViewController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yash
 */
public class ViewStudentDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewStudentDetails
     */
    public ViewStudentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sIdLabel = new javax.swing.JLabel();
        sId = new javax.swing.JTextField();
        fNameLabel = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        lNameLabel = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        sLevelLabel = new javax.swing.JLabel();
        sLevel = new javax.swing.JTextField();
        sResStatusLabel = new javax.swing.JLabel();
        sResStatus = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        gpaLabel = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        phoneLabel = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        editGrade = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        sIdLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sIdLabel.setText("Enter Student ID:");

        sId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fNameLabel.setText("First Name : ");

        fName.setEditable(false);
        fName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lNameLabel.setText("Last Name :");

        lName.setEditable(false);
        lName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dobLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dobLabel.setText("D.O.B(MM-DD-YYYY) :");

        dob.setEditable(false);
        dob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sLevelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sLevelLabel.setText("Student's Level : ");

        sLevel.setEditable(false);
        sLevel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sResStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sResStatusLabel.setText("Student's Residency Status : ");

        sResStatus.setEditable(false);
        sResStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        amountLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        amountLabel.setText("Amount Owed (if any) :");

        amount.setEditable(false);
        amount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        gpaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gpaLabel.setText("GPA :");

        gpa.setEditable(false);
        gpa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        findButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phoneLabel.setText("Phone :");

        phone.setEditable(false);
        phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailLabel.setText("Email :");

        email.setEditable(false);
        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressLabel.setText("Address :");

        address.setEditable(false);
        address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        editGrade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editGrade.setText("Edit GPA");
        editGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGradeActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backButton.setText("Go Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("View Student Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailLabel)
                                .addGap(18, 18, 18)
                                .addComponent(email))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fName)
                                    .addComponent(lName)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sResStatusLabel)
                                .addGap(25, 25, 25)
                                .addComponent(sResStatus))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(amountLabel)
                                .addGap(18, 18, 18)
                                .addComponent(amount))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dob))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(addressLabel)
                                .addGap(18, 18, 18)
                                .addComponent(address))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(gpaLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(editGrade))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(sLevelLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(sLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(sIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(sId, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32)
                                        .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(backButton)))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameLabel)
                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLevelLabel)
                    .addComponent(sLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sResStatusLabel)
                    .addComponent(sResStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpaLabel)
                    .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editGrade))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
         AdminViewController.closeViewStudentDetails();
        AdminViewController.showAdminHomePage();
    }//GEN-LAST:event_backButtonActionPerformed
static int flag=0;
    private void editGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGradeActionPerformed
        // TODO add your handling code here:
        if(flag==0){
        gpa.setEditable(true);
        editGrade.setText("Save Grade");
        flag=1;
        }
        else{
            gpa.setEditable(false);
            editGrade.setText("Edit Grade");
            try {
                SQL_Helper.update_student_gpa(Long.parseLong(sId.getText().trim()),Double.parseDouble(gpa.getText().trim()));
            } catch (SQLException ex) {
                Logger.getLogger(ViewStudentDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            flag=0;
        }
    }//GEN-LAST:event_editGradeActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        
        ArrayList<String> sd= SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim()));
        
        System.out.println("SD has: "+sd);
        fName.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(0).trim());
        lName.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(1).trim());
        dob.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(2).trim());
        sLevel.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(3).trim());
        sResStatus.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(4).trim());
        amount.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(5).trim());
        gpa.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(6).trim());
        phone.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(7).trim());
        email.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(8).trim());
        address.setText(SQL_Helper.get_student_profile(Long.parseLong(sId.getText().trim())).get(9).trim());
    }//GEN-LAST:event_findButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dob;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JButton editGrade;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField gpa;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lName;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField sId;
    private javax.swing.JLabel sIdLabel;
    private javax.swing.JTextField sLevel;
    private javax.swing.JLabel sLevelLabel;
    private javax.swing.JTextField sResStatus;
    private javax.swing.JLabel sResStatusLabel;
    // End of variables declaration//GEN-END:variables
}
