/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.admin;

import Connection.SQL_Helper;
import dbpro.AdminViewController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class ViewCourse extends javax.swing.JPanel {

    /**
     * Creates new form ViewCourse
     */
    public ViewCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        courseLabel = new javax.swing.JLabel();
        courseId = new javax.swing.JTextField();
        courseNameLabel = new javax.swing.JLabel();
        courseName = new javax.swing.JTextField();
        deptNameLabel = new javax.swing.JLabel();
        deptName = new javax.swing.JTextField();
        levelLabel = new javax.swing.JLabel();
        level = new javax.swing.JTextField();
        gpaLabel = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        prereqLabel = new javax.swing.JLabel();
        spApprovalLabel = new javax.swing.JLabel();
        spApproval = new javax.swing.JTextField();
        creditsLabel = new javax.swing.JLabel();
        credits = new javax.swing.JTextField();
        show = new javax.swing.JButton();
        back = new javax.swing.JButton();
        preReq = new javax.swing.JTextField();
        preGradeLabel = new javax.swing.JLabel();
        preGrade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField6.setText("jTextField6");

        courseLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        courseLabel.setText("Course Id :");

        courseId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        courseNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        courseNameLabel.setText("Course Name :");

        courseName.setEditable(false);
        courseName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        deptNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deptNameLabel.setText("Department Name :");

        deptName.setEditable(false);
        deptName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        levelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        levelLabel.setText("Level :");

        level.setEditable(false);
        level.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        gpaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gpaLabel.setText("GPA Requirement(if any) :");

        gpa.setEditable(false);
        gpa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        prereqLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prereqLabel.setText("List of prerequisite courses :");

        spApprovalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spApprovalLabel.setText("Special Approval Required :");

        spApproval.setEditable(false);
        spApproval.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        creditsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        creditsLabel.setText("Number Of Credits :");

        credits.setEditable(false);
        credits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsActionPerformed(evt);
            }
        });

        show.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        preReq.setEditable(false);
        preReq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        preGradeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        preGradeLabel.setText("PreReq Grades :");

        preGrade.setEditable(false);
        preGrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("View Course :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preGradeLabel)
                        .addGap(27, 27, 27)
                        .addComponent(preGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(spApprovalLabel)
                            .addGap(18, 18, 18)
                            .addComponent(spApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(prereqLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(preReq))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(gpaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(gpa))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(levelLabel)
                            .addGap(18, 18, 18)
                            .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(deptNameLabel)
                            .addGap(18, 18, 18)
                            .addComponent(deptName, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(courseNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(courseName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creditsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(credits, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courseLabel)
                        .addGap(18, 18, 18)
                        .addComponent(courseId, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(show)
                        .addGap(18, 18, 18)
                        .addComponent(back)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLabel)
                    .addComponent(courseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show)
                    .addComponent(back))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseNameLabel)
                    .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptNameLabel)
                    .addComponent(deptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpaLabel)
                    .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prereqLabel)
                    .addComponent(preReq, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preGradeLabel)
                    .addComponent(preGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spApprovalLabel)
                    .addComponent(spApproval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditsLabel)
                    .addComponent(credits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         AdminViewController.closeViewCourse();
        AdminViewController.showViewAddCourse();
    }//GEN-LAST:event_backActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed

            // TODO add your handling code here:
            ArrayList<String> course= SQL_Helper.get_course_details(courseId.getText().trim());
            
            System.out.println(course + "Size is:"+ course.size());
            
            
            courseName.setText(course.get(0));
            deptName.setText(course.get(1));
            level.setText(course.get(2));
            gpa.setText(course.get(3));
            preReq.setText(course.get(4));
            preGrade.setText(course.get(5));
            spApproval.setText(course.get(6));
            if(course.get(7).equals(course.get(8)))
                    credits.setText(course.get(7));
            else if(course.get(8) == null)
                    credits.setText(course.get(7));
            else
              credits.setText(course.get(7)+" - "+course.get(8));  
            
       
        
    }//GEN-LAST:event_showActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField courseId;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JTextField courseName;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField credits;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JTextField deptName;
    private javax.swing.JLabel deptNameLabel;
    private javax.swing.JTextField gpa;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField level;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField preGrade;
    private javax.swing.JLabel preGradeLabel;
    private javax.swing.JTextField preReq;
    private javax.swing.JLabel prereqLabel;
    private javax.swing.JButton show;
    private javax.swing.JTextField spApproval;
    private javax.swing.JLabel spApprovalLabel;
    // End of variables declaration//GEN-END:variables
}
